parameters:
#    minsalsifda.example.class: Minsal\sifdaBundle\Example

services:
#    minsalsifda.example:
#        class: %minsalsifda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
